name: badua_coverage

on:
  push:
    branches: ["ISW2"]
  pull_request:
    branches: ["ISW2"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'temurin'
      - name: Clone and build ba-dua  # to get the CLI
        run: |
          git clone https://www.github.com/saeg/ba-dua.git
          cd ba-dua
          git checkout badua/ba-dua-0.6.0 -b ba-dua-0.6.0
          mvn clean install
        working-directory: ${{ github.workspace }}
      - name: Build
        run: mvn -P badua test
        working-directory: ${{ github.workspace }}
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: badua-report
          path: bookkeeper-server/target/badua.xml
          if-no-files-found: error