name: pit_coverage

on:
  push:
    branches: ["ISW2"]
  pull_request:
    branches: ["ISW2"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build
        run: mvn clean test -P pitest
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          name: pit-report
          path: bookkeeper-server/target/pit-reports
          if-no-files-found: error